### ISSUE TITLE
Local file inclusion vulnerability

### ISSUE THREAD

**Issue by Holyshatots** [bjohnmer/pdvsa#1]
In `dxnutricional/index.php` on line 30:
```
 include($_GET['p'].'.php'); 
```
there is a local file inclusion vulnerability. `p` is not sanitized and by using a null byte character can be used to include any file on the server. [More information](http://resources.infosecinstitute.com/file-inclusion-attacks/)

**Comment by bjohnmer** [comment]
Thanks, this is a project that I made long time ago, thanks I will fix it
